package com.theladders.solid.dip.suggestedarticleexample;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by lliao on 6/13/14.
 */
public class SuggestedArticleExampleImpl implements SuggestedArticleExample
{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    protected List<GeneralCriteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    private CriteriaFactory criteriaFactory;
    private String criteria;

    public void setCriteria(String criteria){
        this.criteria = criteria;
    }

    public SuggestedArticleExampleImpl()
    {
        criteriaFactory = new CriteriaFactory();
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public List<GeneralCriteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public void or(GeneralCriteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public GeneralCriteria or() {
        GeneralCriteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */
    public GeneralCriteria createCriteria() {
        GeneralCriteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suggested_article
     *
     * @mbggenerated Fri Dec 03 17:06:47 EST 2010
     */


    protected GeneralCriteria createCriteriaInternal() {
        GeneralCriteria criteria = criteriaFactory.generateCriteria(this.criteria);
        return criteria;
    }
}
